### ISSUE TITLE
[BUG] [camera_x]: None of the specified AF/AE/AWB MeteringPoints is supported on this camera

### ISSUE THREAD

**Issue by victortive** [fluttercandies/flutter_wechat_camera_picker#262] opened 2024-07-18 15:16 UTC
**Describe the bug**

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: CameraException(java.lang.IllegalArgumentException: None of the specified AF/AE/AWB MeteringPoints is supported on this camera., IllegalArgumentException)
       at CameraController.setFocusMode(camera_controller.dart:834)
       at CameraPickerState.wrapControllerMethod(camera_picker_state.dart:327)
       at Future.wait.<fn>(dart:async)
       at CameraPickerState.takePicture(camera_picker_state.dart:900)
```

**How to reproduce**

4. Error occurred.

**Expected behavior**

**Screenshots (If contains)**

**Version information**

- Device: [Galaxy Tab S9 Ultra]
- OS: [Android 14]
- Package Version: [4.3.1]
- Flutter Version: [3.22.2]

**Additional context**

**Comment by victortive** [comment] 2024-07-18 15:23
I am still looking for a way to reproduce. Will update.

**Comment by AlexV525** [comment] 2024-08-21 02:41
This is related to the `camera_avfoundation` which is not caused by the plugin. Closing.

**Closed by AlexV525** 2024-08-21 02:41 UTC
Labels: await investigate

**Comment by victortive** [comment] 2024-10-17 21:03
I was able to reproduce this issue on android when calling. The issue happens only the first time and only when there is a `CameraPickerConfig` provided.
 
```dart
final entity = await CameraPicker.pickFromCamera(
      context,
      pickerConfig: const CameraPickerConfig(
        preferredLensDirection: CameraLensDirection.front,
      ),
    );
```
