### ISSUE TITLE
[QUESTION] Size of image picked

### ISSUE THREAD

**Issue by baptistesx** [fluttercandies/flutter_wechat_camera_picker#163] opened 2023-02-28 12:33 UTC
Hi there!

i got a question:

When i pick a image from the gallery, I'm getting the File correctly.

then i print its sized with: print(file.lengthSync());

Getting: 8364495 which is about 8Mo right?

The thing is when i check the image details in the gallery, i see 3.6Mo
<img width="260" alt="image" src="https://user-images.githubusercontent.com/9638281/221855229-97c563c1-8767-44bd-af96-e62ba77ad080.png">

Any idea why? am i missing something?

Thanks in advance :)

**Comment by AlexV525** [comment] 2023-04-24 01:59
Duplicate of https://github.com/fluttercandies/flutter_photo_manager/issues/928.

**Closed by AlexV525** 2023-04-24 01:59 UTC
Labels: await investigate
